<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Hellang.Middleware.ProblemDetails" Version="6.5.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CMS.Application\CMS.Application.csproj" />
		<ProjectReference Include="..\CMS.Domain\CMS.Domain.csproj" />
	</ItemGroup>
	
	
</Project>
