<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\20231002091202_CVnotrequiereddana.cs" />
    <Compile Remove="Migrations\20231002091202_CVnotrequiereddana.Designer.cs" />
    <Compile Remove="Migrations\20231003090242_CVnotReqdana.cs" />
    <Compile Remove="Migrations\20231003090242_CVnotReqdana.Designer.cs" />
    <Compile Remove="Migrations\20231009074816_fixingPositionIdinCandidates.cs" />
    <Compile Remove="Migrations\20231009074816_fixingPositionIdinCandidates.Designer.cs" />
    <Compile Remove="Migrations\20231009075338_fixingPositionIdinCandidates.cs" />
    <Compile Remove="Migrations\20231009075338_fixingPositionIdinCandidates.Designer.cs" />
    <Compile Remove="Migrations\20231009093958_removenullableFromCountryIdInCandidates.cs" />
    <Compile Remove="Migrations\20231009093958_removenullableFromCountryIdInCandidates.Designer.cs" />
    <Compile Remove="Migrations\20231009095455_makeCountryIdNulableInCandidates.cs" />
    <Compile Remove="Migrations\20231009095455_makeCountryIdNulableInCandidates.Designer.cs" />
    <Compile Remove="Migrations\20231009141131_changedDatabaseServerToOld.cs" />
    <Compile Remove="Migrations\20231009141131_changedDatabaseServerToOld.Designer.cs" />
    <Compile Remove="Migrations\20231009185620_makePositionIdNullable.cs" />
    <Compile Remove="Migrations\20231009185620_makePositionIdNullable.Designer.cs" />
    <Compile Remove="Migrations\20231012112333_removeNullableFromCvAttachmentInCandidate.cs" />
    <Compile Remove="Migrations\20231012112333_removeNullableFromCvAttachmentInCandidate.Designer.cs" />
    <Compile Remove="Migrations\20231016103207_ActualExperienceNullable.cs" />
    <Compile Remove="Migrations\20231016103207_ActualExperienceNullable.Designer.cs" />
    <Compile Remove="Migrations\20231017205811_fixed.cs" />
    <Compile Remove="Migrations\20231017205811_fixed.Designer.cs" />
    <Compile Remove="Migrations\20231018103009_secondInterviewer.cs" />
    <Compile Remove="Migrations\20231018103009_secondInterviewer.Designer.cs" />
    <Compile Remove="Migrations\20231207083444_AddNullAbleToPositionId.cs" />
    <Compile Remove="Migrations\20231207083444_AddNullAbleToPositionId.Designer.cs" />
    <Compile Remove="Migrations\20240107072228_addingTrack.cs" />
    <Compile Remove="Migrations\20240107072228_addingTrack.Designer.cs" />
    <Compile Remove="Migrations\20240107072515_addTrack.cs" />
    <Compile Remove="Migrations\20240107072515_addTrack.Designer.cs" />
    <Compile Remove="Migrations\20240107072744_addTrack.cs" />
    <Compile Remove="Migrations\20240107072744_addTrack.Designer.cs" />
    <Compile Remove="Migrations\20240107073110_addTracj=k.cs" />
    <Compile Remove="Migrations\20240107073110_addTracj=k.Designer.cs" />
    <Compile Remove="Migrations\20240107073134_addTrack.cs" />
    <Compile Remove="Migrations\20240107073134_addTrack.Designer.cs" />
    <Compile Remove="Migrations\20240107073831_addTrack.cs" />
    <Compile Remove="Migrations\20240107073831_addTrack.Designer.cs" />
    <Compile Remove="Migrations\20240107074318_addTrack.cs" />
    <Compile Remove="Migrations\20240107074318_addTrack.Designer.cs" />
    <Compile Remove="Migrations\20240108062926_test.cs" />
    <Compile Remove="Migrations\20240108062926_test.Designer.cs" />
    <Compile Remove="Migrations\20240108063138_test.cs" />
    <Compile Remove="Migrations\20240108063138_test.Designer.cs" />
    <Compile Remove="Migrations\20240108063447_test.cs" />
    <Compile Remove="Migrations\20240108063447_test.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="SQL_SCRIPTS\01_CreateConfigrationTables.sql" />
    <None Include="SQL_SCRIPTS\02_Create_SelectedInterviewers_Table.sql" />
    <None Include="SQL_SCRIPTS\03_InsertDataToWorkflowConfig.sql" />
    <None Include="SQL_SCRIPTS\04_UpdateOldData.sql" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
